**Import mnist, PIL, sklearn libraries**

In [1]:
import mnist
from PIL import Image
import numpy as np
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix

**Train & Test**

In [2]:
x_train = mnist.train_images()
y_train = mnist.train_labels()

x_test = mnist.test_images()
y_test = mnist.test_labels()

x_train = x_train.reshape((-1, 28*28))
x_test = x_test.reshape((-1, 28*28))

**Optimize model by scale dataset**

In [3]:
x_train = (x_train/256)
x_test = (x_test/256)

print('x_train', x_train)
print('x_test', x_test)
print('y_train', y_train)

x_train [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
x_test [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
y_train [5 0 4 ... 5 6 8]


**Dimesions**

In [4]:
print(x_train.ndim)
print(x_test.shape)

2
(10000, 784)


**optimize model by scale dataset**

In [5]:
x_train = (x_train/256)
x_test = (x_test/256)

In [7]:
clf = MLPClassifier(solver='adam', activation='relu', hidden_layer_sizes=(64*64))
clf.fit(x_train, y_train)

/usr/local/lib/python3.8/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:699: UserWarning: Training interrupted by user.
  warnings.warn("Training interrupted by user.")


MLPClassifier(hidden_layer_sizes=4096)